{{- if .Values.highAvailability.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "redpanda-gke.fullname" . }}-pdb
  namespace: {{ include "redpanda-gke.namespace" . }}
  labels:
    {{- include "redpanda-gke.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.highAvailability.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "redpanda-gke.selectorLabels" . | nindent 6 }}
{{- end }}
