---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: {{ .Values.storage.storageClassName }}
  labels:
    {{- include "redpanda-gke.labels" . | nindent 4 }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: {{ .Values.storage.gke.type }}
  replication-type: {{ .Values.storage.gke.replicationType }}
  fstype: {{ .Values.storage.gke.fsType }}
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: {{ .Values.storage.allowVolumeExpansion }}
reclaimPolicy: {{ .Values.storage.reclaimPolicy }}
